name: Consumer Workflow

on:
  repository_dispatch:
    types: [trigger-consumer-workflow]

jobs:
  verify-contract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Consumer Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout Stubs Repository
        uses: actions/checkout@v2
        with:
          repository: duttabhishek0/temp-stubs
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: temp-stubs

      - name: Run Consumer Tests
        env:
          STUBS_PATH: ./temp-stubs  # Ensure the test uses this path
          SPRING_CLOUD_CONTRACT_STUBRUNNER_REPOSITORY_ROOT: ./temp-stubs  # Point StubRunner to the local stubs
          SPRING_CLOUD_CONTRACT_STUBRUNNER_CLASSIFIER: stubs
          SPRING_CLOUD_CONTRACT_STUBRUNNER_IDS: com.example:productservice:0.0.1-SNAPSHOT:stubs:8080
        run: |
            mvn test
