name: Consumer Workflow

on:
  repository_dispatch:
    types: [trigger-consumer-workflow]

jobs:
  verify-contract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17' 
        distribution: 'temurin'

    - name: Run Consumer Tests
      run: mvn test
