name: Consumer Workflow

on:
  repository_dispatch:
    types: [trigger-consumer-workflow]

jobs:
  verify-contract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Consumer Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout Stubs Repository
        uses: actions/checkout@v2
        with:
          repository: duttabhishek0/temp-stubs
          ref: main
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: temp-stubs

      - name: Run Consumer Tests
        env:
          STUBS_PATH: ./stubs  # Path to where the stubs are checked out
        run: |
          mvn test -Dstubrunner.stubsMode=LOCAL \
                   -Dstubrunner.ids=com.example:productservice:+:stubs:8080 \
                   -Dstubrunner.repositoryRoot=file:///${{ github.workspace }}/temp-stubs \
